---
title: Members of the ART Lab
toc: true
toc-location: left
---

# Principal Investigator

## [Dr. Robert Schlauch](https://scholar.google.com/citations?user=S7kibPcAAAAJ&hl=en&oi=ao)

My research interests focus broadly in understanding the role of individual differences in alcohol and drug use behavior. Specifically, I am interested in applying multidisciplinary approaches to the study of: a) processes associated with positive treatment outcomes, with a particular emphasis on craving and pretreatment change, b) risk factors for the development of substance use disorders (SUDs), including positive and negative reinforcement pathways to use, c) the interplay between substance use, comorbid disorders, personality, and aggression, including intimate partner violence, and d) the moderating role of individual difference variables in alcohol related disinhibited behaviors. Related to my work on craving, I am also interested (in collaboration with Dr. Diana Rancourt) in the applicability of craving as a transdiagnostic construct for disordered eating and compensatory behaviors. Secondary interests include methodological issues in clinical science broadly, and substance use research specifically.

# Post-Doctoral Researchers

*Coming-Soon! Contact Dr. Schlauch if interested!*

# Graduate Students

## Brendan Walsh

## Gaelle El Helou

## Alex Rivera

## Charlie Manzler

## Jared Davis

# Undergraduate Students

- J.D. Dato 
  - [Website](https://jd-dato.github.io)

- IDK the others like that tho...
